---
version: '3.9'
services:
  flyway:
    image: 'flyway/flyway:7.3.1'
    container_name: 'the-gear-of-seasons_flyway'
    hostname: 'the-gear-of-seasons_flyway'
    restart: 'no'
    volumes:
      - ./db/flyway_data/sql:/flyway/sql
      - ./db/flyway_data/conf:/flyway/conf
    networks:
      - 'the-gear-of-seasons-link'
    profiles: ['tool']

  postgres:
    image: 'postgres:alpine'
    container_name: 'the-gear-of-seasons_db'
    hostname: 'the-gear-of-seasons_db'
    user: "${UID}:${GID}"
    environment:
      POSTGRES_DB: 'the-gear-of-seasons'
      POSTGRES_USER: 'the-gear-of-seasons'
      POSTGRES_PASSWORD: 'the-gear-of-seasons'
      POSTGRES_INITDB_ARGS: '--encoding=UTF8'
      TZ: 'Asia/Tokyo'
      PGTZ: 'Asia/Tokyo'
    expose:
      - '5432'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - './var/postgres:/var/lib/postgresql/data:z'
      - './db/helpers:/helpers'
      - '/etc/passwd:/etc/passwd:ro'
    networks:
      - 'the-gear-of-seasons-link'
    tty: true
    stdin_open: true

networks:
  default:
    driver: 'null'
  the-gear-of-seasons-link:
    external: false
