name: Build on Windows

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - magistra

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '> 1.15.0'
      - uses: actions/setup-node@v2
      - name: Build
        run: npm run build
