name: Build on Linux

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - magistra

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '> 1.15.0'
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '> 14.0'
          check-latest: true
      - name: Build
        run: |
          npm install
          npm run build
